# Generated by Django 6.0.3 on 2026-04-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeypot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attacklog',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='attacklog',
            unique_together={('ip_address', 'username_attempted', 'password_attempted', 'timestamp')},
        ),
    ]
