# Generated by Django 6.0.3 on 2026-04-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeypot', '0002_alter_attacklog_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attacklog',
            name='attack_reason',
            field=models.TextField(blank=True, help_text='Reason for classification'),
        ),
        migrations.AddField(
            model_name='attacklog',
            name='is_attacker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attacklog',
            name='threat_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attacklog',
            name='user_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Suspicious', 'Suspicious'), ('Attacker', 'Attacker')], default='Normal', max_length=20),
        ),
    ]
