# Generated by Django 4.2.7 on 2026-03-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45)),
                ('username_attempted', models.CharField(max_length=100)),
                ('password_attempted', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.TextField()),
                ('attack_type', models.CharField(default='Brute Force', max_length=50)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
